Porting to Ultra96 and DFX
necst/entree pull request #3
Opened 2022-05-10 14:24 UTC by matsant01

2022-05-10 14:52 UTC, andredami requested changes
CRITICAL: remove `trees_per_class` parameter! Iterate on the `ensemble_dict` instead.

MINOR: remove all "newline" style approach inherited from `writer.py`

2022-05-10 14:52 UTC, andredami commented on examples/partial_dynamic_reconfiguration.py
> +cfg['TreesPerClass'] = "6"
MUST BE COMPUTED from the DT ensemble!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +        n_trees_per_class = int(cfg['TreesPerClass'])
Fetch directly from the DT ensemble

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                TreesPerClass=int(cfg['TreesPerClass']),
Duplicated! See variable above!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +            for j in range(n_trees_per_class):
You should iterate over the list of trees available in the ensemble_dict!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                TreesPerClass=int(cfg['TreesPerClass']),
BTW, should be removed completelly!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                set_properties=set_properties,
Bad naming! Set propoerties looks like a method\function!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                num1=int((2**math.ceil(math.log(precision, 2)))*ensemble_dict['n_features']),
num1,2,3 are a non informative names.

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +set n_trees_per_class {{TreesPerClass}}
Should not be here! Trees per class is not a given parameter.

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +# Currently support Ultrascale+
Should support both! (FUTURE FEATURE! POSTPONED) (ADD A TODO!)

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +{%- set ns=namespace(newline='') %}
"newline" (similar to writer.py) variable is not needed any more! The template can be directly constructed using the loop.

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +set sample_length {{num1}}
num1,2,3 are not informative!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +set n_trees_per_class {{trees_per_class}}
Trees per class is not a given parameter!

2022-05-10 14:52 UTC, andredami commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +{%- set ns=namespace() %}
No newline approach (~ witer.py). Output directly.

2022-05-10 19:13 UTC, matsant01 commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +set n_trees_per_class {{TreesPerClass}}
I'm stuck trying to understand how trees are distributed in the different classes.
I've tried launching debug as you suggested but it stops immediately giving No module named entree error.

2022-05-10 19:14 UTC, matsant01 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Updating entree to DFX](https://trello.com/c/yaoZkc5i/26-updating-entree-to-dfx)

2022-05-10 19:28 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +set n_trees_per_class {{TreesPerClass}}
Hum ... looks like you are not starting the debugger in the right virtual environment where entree is installed

2022-05-13 07:10 UTC, matsant01 commented on entree/backends/xilinxhls/writer.py
> +                num1=int((2**math.ceil(math.log(precision, 2)))*ensemble_dict['n_features']),
In the case of synth_and_impl those variables were useless, so they've been removed

2022-05-13 09:42 UTC, matsant01 commented on entree/backends/xilinxhls/writer.py
> +        n_trees_per_class = int(cfg['TreesPerClass'])
I've created a list called tree_in_classes that counts for each class the number of trees.

2022-05-13 15:21 UTC, matsant01 commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +set n_trees_per_class {{trees_per_class}}
Replaced with list of number of trees in each class

2022-05-27 13:19 UTC, andredami requested changes
Restructure the jinja template to eliminate old writer-like approach to new lines and indents. ask @FedericoDD!

2022-05-27 13:19 UTC, andredami commented on examples/partial_dynamic_reconfiguration.py
> +# NOTE: if not set, the nJobs will be set to total number of cores minus two
This note does not make sense here.
Remove it.

2022-05-27 13:19 UTC, andredami commented on examples/partial_dynamic_reconfiguration.py
> +cfg['nJobs'] = "12"
Shouldn't be part of the example. Remove it.

2022-05-27 13:19 UTC, andredami commented on examples/partial_dynamic_reconfiguration.py
> +cfg['Precision'] = "ap_fixed<8,4>"
Shouldn't be part of the example. Remove it.

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +import shutil
`copyfile` from shutil is already imported two lines below.
Use that directly

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +        list = [[] for i in range(n_banks*n_trees_per_bank)]
did you mean `list = [] * (n_banks*n_trees_per_bank)`?

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +        set_properties=[]
set_properties look like the name of a function\method.

Verbs are for functions\method, Nouns for attributes\properties.

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +        list = [[] for i in range(n_banks*n_trees_per_bank)]
Redefining list, which is a special term, is a risk! Use meaningful names!

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                set_properties = set_properties,
(see above)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                set_properties = set_properties,
(see above)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +              'autoFloorplanning': True }
Does not belong this PR!!! (Never mix concerns from different PRs - this time, leave it anyway)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +# Create reconfigurable modules as block design containing single tree IPs
You are forgetting to create the BD for the IDLE TREE IP (see myproject.cpp.jinja for interface)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +		create_bd_cell -type container -reference tree_rm_${i_class}_${j_tree_in_class} tree_rm_${i_class}_${j_tree_in_class}
Create the BD cell always with the IDLE TREE (See above)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +		set_property -dict [list CONFIG.ENABLE_DFX {true}] [get_bd_cells tree_rm_${i_class}_${j_tree_in_class}]
Allways assing for DFX the IDLE TREE as Default (See above)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +		set_property name tree_rp_${i}_${j} [get_bd_cells tree_rm_${i_class}_${j_tree_in_class}]
The name could be set directly in `create_bd_cell` (replace the last `tree_rm_${i_class}_${j_tree_in_class}`)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +{%- set ns=namespace(newline='') %}
Remove the newline and create template directly!

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/top_system.tcl.jinja
> +{%- set ns=namespace(newline='') %}
Refactor this whole block to include always the IDLE TREE and check that this works with n_estimators to 1, 2, 6 for the iris example in `partial_dynamic_reconfiguration.py` (currently not working!)

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +{%- set ns=namespace() %}
Remove the NEWLINE APPROACH!

2022-05-27 13:19 UTC, andredami commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +{{' '}}impl_1
(see above)

2022-05-27 18:52 UTC, matsant01 commented on entree/backends/xilinxhls/system-template/synth_and_impl.tcl.jinja
> +{{' '}}impl_1
I will schedule a meeting with @FedericoDD to look to this part of the code that he wrote (I think it will be easier, or at least faster to exploit his knowledge rather than getting started with jinja by myself)

2022-05-29 19:03 UTC, matsant01 commented on entree/backends/xilinxhls/writer.py
> +        list = [[] for i in range(n_banks*n_trees_per_bank)]
No, that syntax means that list (now called rm_in_rp_list) is a list of (n_banks*n_trees_per_bank) lists.

2022-06-08 11:10 UTC, andredami commented
[TESTED] Static accelerator

2022-07-18 13:19 UTC, andredami approved these changes

2022-07-18 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
>          template.stream(
Is this still true?
If so, this limitation must be removed.

2022-07-18 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +    if cfg.get('autoFloorplanning', False) == True:
If autoFloorplanning is not enabled, there is no PBlock definition from the basic config file?
The default file should be used instead!

2022-07-18 13:19 UTC, andredami commented on entree/backends/xilinxhls/writer.py
> +                rm_in_rp_list[i * n_trees_per_bank + j].append("tree_rm_idle")
Here it looks like you are adding the idle tree but different sources contain a TODO on this.

2022-07-18 13:27 UTC, andredami approved these changes

2022-07-18 13:27 UTC, merged